# User config
author: "AYOWHATSUP"
tagline: "Pineapple Certfied Jekyll Theme"
description: "KDT 깃블로그 만들기 프로젝트"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "bluelily555@daum.net"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/bluelily555"

# Site config
baseurl: "/giblog_hello2"
#url: "https://bluelily555.github.io"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
